(unwatch all)
(clear)
(set-strategy depth)
(open "chksyntx.rsl" chksyntx "w")
(dribble-on "chksyntx.out")
(batch "chksyntx.bat")
(dribble-off)
(load "compline.clp")
(printout chksyntx "chksyntx.bat differences are as follows:" crlf)
(compare-files chksyntx.exp chksyntx.out chksyntx)
(close chksyntx)
