(unwatch all)
(clear)
(setgen 1)
(dribble-on "dftmpfun.out")
(batch "dftmpfun.bat")
(dribble-off)
(clear)
(open "dftmpfun.rsl" dftmpfun "w")
(load "compline.clp")
(printout dftmpfun "dftmpfun.bat differences are as follows:" crlf)
(compare-files dftmpfun.exp dftmpfun.out dftmpfun)
(close dftmpfun)
