(unwatch all)
(clear)
(load fctquery.clp)
(dribble-on "fctquery.out")
(batch "fctquery.bat")
(dribble-off)
(clear)
(open "fctquery.rsl" fctquery "w")
(load "compline.clp")
(printout fctquery "fctquery.clp differences are as follows:" crlf)
(compare-files fctquery.exp fctquery.out fctquery)
(close fctquery)
